version: '3'
services:
  webserver:
    image: nginx:1.13.5-alpine
    container_name: nginx
    volumes:
      - ./html:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"